### ISSUE TITLE
Only 2 block success when import command the other fails

### ISSUE THREAD

**Issue by moysoft** [luyadev/luya-composer#10]
while import command

Unable to process block definition 'vendor\luyadev/luya-bootstrap3\src/blocks'
Unable to process block definition 'vendor\luyadev/luya-generic\src/blocks'
Unable to process block definition 'vendor\luyadev/luya-module-cms\src/frontend/blocks'
only 2 block success
how to resolve this issues

**Comment by nadar** [comment]
Ok thanks for the report, it looks like the pats are wrong on windows, see `vendor\\luyadev/luya-generic\\src/blocks` this be `vendor\\luyadev\\luya-generic\\src\\blocks` i assume? could you try to adjust the this paths in the installer.php and run `luya import` again? Thanks for the report.

**Comment by nadar** [comment]
Btw. i assume this is also due to a definition which should be platform independent:

```
"extra": {
        "luya" : {
        	"blocks" : ["src/frontend/blocks"]
        }
    }
```

**Comment by nadar** [comment]
We could use ` ["src{{DS}}frontend{{DS}}blocks"]` which then would be replaced with the current DIRECTORY_SEPERATOR

**Comment by EyrikhVI** [comment]
luya\cms\admin\importers\BlockImporter:
╔═════╤═══════════════════════════════════════════════════════════════════════════════════════════════════╗
║ Key │ Value                                                                                             ║
╟─────┼───────────────────────────────────────────────────────────────────────────────────────────────────╢
║ 0   │ block \luya\cms\frontend\blocks\HtmlBlock: remains the same, nothing to update                    ║
╟─────┼───────────────────────────────────────────────────────────────────────────────────────────────────╢
║ 1   │ block \luya\cms\frontend\blocks\ModuleBlock: remains the same, nothing to update                  ║
╟─────┼───────────────────────────────────────────────────────────────────────────────────────────────────╢
║ 2   │ Unable to process block definition 'vendor\luyadev/luya-bootstrap3\src/blocks'                    ║
╟─────┼───────────────────────────────────────────────────────────────────────────────────────────────────╢
║ 3   │ Unable to process block definition 'vendor\luyadev/luya-generic\src/blocks'                       ║
╟─────┼───────────────────────────────────────────────────────────────────────────────────────────────────╢
║ 4   │ Unable to process block definition 'vendor\luyadev/luya-module-cms\src{{DS}}frontend{{DS}}blocks' ║
╟─────┼───────────────────────────────────────────────────────────────────────────────────────────────────╢
║ 5   │ Block importer finished with 2 blocks.                                                            ║
╚═════╧═══════════════════════════════════════════════════════════════════════════════════════════════════╝

[src.zip](https://github.com/luyadev/luya-composer/files/3150309/src.zip)
[installer.zip](https://github.com/luyadev/luya-composer/files/3150312/installer.zip)

**Comment by nadar** [comment]
Hey @EyrikhVI i think you was a little to fast :-) I will now implement this behavior for generic blocks, afterwards you can use dev-master of luya composer and luya generic blocks inside your composer.json, remove vendor and run composer update to test.

**Comment by nadar** [comment]
in require section

```
"luyadev/luya-composer" : "dev-master",
"luyadev/luya-generic" : "dev-master"
```

make sure to remove vendor folder and run composer update. Please post the installer.php file here afterwards.

**Comment by nadar** [comment]
@EyrikhVI @moysoft 

Could you please try those steps i mentioned above? Adding dev-master of luya composer and dev-master of LUYA generic and post the installer.php file result here?

**Comment by EyrikhVI** [comment]
I performed:
Use global DS variable  …
add package folder name #10
In which file do I need to run: 
in require section
"luyadev/luya-composer" : "dev-master",
"luyadev/luya-generic" : "dev-master"
make sure to remove vendor folder and run composer update. Please post the installer.php file here afterwards.

**Comment by nadar** [comment]
The use of global {{DS}} variable must be done in luya generic, so i did that for you, you just have to install the dev-master of this package.

Maybe you forgot the installer.php file? :-)

**Comment by EyrikhVI** [comment]
[installer.zip](https://github.com/luyadev/luya-composer/files/3152173/installer.zip)

**Comment by nadar** [comment]
This is not the latest luya composer version. What does your composer.json look like?

**Comment by EyrikhVI** [comment]
[installer.zip](https://github.com/luyadev/luya-composer/files/3152229/installer.zip)

**Comment by nadar** [comment]
this looks good now! `vendor\\luyadev\\luya-generic\\src\\blocks',` could you try to run the import command and see if generic blocks are imported now?

**Comment by EyrikhVI** [comment]
luya\cms\admin\importers\BlockImporter:
╔═════╤═════════════════════════════════════════════════════════════════════════════════════════╗
║ Key │ Value                                                                                   ║
╟─────┼─────────────────────────────────────────────────────────────────────────────────────────╢
║ 0   │ block \luya\cms\frontend\blocks\HtmlBlock: remains the same, nothing to update          ║
╟─────┼─────────────────────────────────────────────────────────────────────────────────────────╢
║ 1   │ block \luya\cms\frontend\blocks\ModuleBlock: remains the same, nothing to update        ║
╟─────┼─────────────────────────────────────────────────────────────────────────────────────────╢
║ 2   │ Unable to process block definition 'vendor\luyadev\luya-generic\src\blocks'             ║
╟─────┼─────────────────────────────────────────────────────────────────────────────────────────╢
║ 3   │ Unable to process block definition 'vendor\luyadev\luya-bootstrap3\src/blocks'          ║
╟─────┼─────────────────────────────────────────────────────────────────────────────────────────╢
║ 4   │ Unable to process block definition 'vendor\luyadev\luya-module-cms\src/frontend/blocks' ║
╟─────┼─────────────────────────────────────────────────────────────────────────────────────────╢
║ 5   │ Block importer finished with 2 blocks.                                                  ║
╚═════╧═════════════════════════════════════════════════════════════════════════════════════════╝

**Comment by nadar** [comment]
But on a windows system this path looks correct for me: ` 'vendor\luyadev\luya-generic\src\blocks'` Is the folder structure correct? Can you ensure this folders exists with this writing? What is the current working directory? How do you run the import command?

**Comment by EyrikhVI** [comment]
Full path C:\OSPanel\domains\contestofidea.loc\luya-kickstarter\vendor\luyadev\luya-generic\src\blocks The folder is open for writing.  Is the folder structure correct? - Yes
Import:
Валерий@EYRIKH-HP c:\OSPanel\domains\contestofidea.loc\luya-kickstarter\public_html                       
$ php index.php import                                                                                    
LUYA import command (based on LUYA 1.0.17)                                                                
                                                                                                          
luya\cms\admin\importers\BlockImporter:                                                                   
╔═════╤═════════════════════════════════════════════════════════════════════════════════════════╗         
║ Key │ Value                                                                                   ║         
╟─────┼─────────────────────────────────────────────────────────────────────────────────────────╢         
║ 0   │ block \luya\cms\frontend\blocks\HtmlBlock: remains the same, nothing to update          ║         
╟─────┼─────────────────────────────────────────────────────────────────────────────────────────╢         
║ 1   │ block \luya\cms\frontend\blocks\ModuleBlock: remains the same, nothing to update        ║         
╟─────┼─────────────────────────────────────────────────────────────────────────────────────────╢         
║ 2   │ Unable to process block definition 'vendor\luyadev\luya-generic\src\blocks'             ║         
╟─────┼─────────────────────────────────────────────────────────────────────────────────────────╢         
║ 3   │ Unable to process block definition 'vendor\luyadev\luya-bootstrap3\src/blocks'          ║         
╟─────┼─────────────────────────────────────────────────────────────────────────────────────────╢         
║ 4   │ Unable to process block definition 'vendor\luyadev\luya-module-cms\src/frontend/blocks' ║         
╟─────┼─────────────────────────────────────────────────────────────────────────────────────────╢         
║ 5   │ Block importer finished with 2 blocks.                                                  ║         
╚═════╧═════════════════════════════════════════════════════════════════════════════════════════╝         

If I do so
Валерий@EYRIKH-HP c:\OSPanel\domains\contestofidea.loc\luya-kickstarter
$ php c:\OSPanel\domains\contestofidea.loc\luya-kickstarter\public_html\index.php import
then only:
LUYA import command (based on LUYA 1.0.17)
Importer run successful.

**Comment by nadar** [comment]
Why is `vendor\luyadev\luya-generic\src\blocks` not a valid path? Could you please elaboraty this? This is the code part which try's to load the path: https://github.com/luyadev/luya-module-cms/blob/248c1803b246a40bbae482ff6b409720dc469211/src/admin/importers/BlockImporter.php#L86-L92

**Comment by nadar** [comment]
@EyrikhVI Maybe you could also dump getcwd() somewhere next to this lines in your vendor folder to see in which directory the importer is when checking is_dir against the path.

**Comment by nadar** [comment]
@EyrikhVI I did those test by myself, so the problem is that you have to run `php index.php import` inside the public_html folder, and the current cwd will be: `"C:\Users\XYZ\Desktop\luya-kickstarter\public_html"` but the path to the blocks is relative based on the base path of the app: `vendor\luyadev\luya-generic\src\blocks` which of course could not be found.

**Comment by nadar** [comment]
https://github.com/luyadev/luya-module-cms/pull/193

**Comment by EyrikhVI** [comment]
Sorry for the long silence. I realized that the problem is with the system directories. Do you need any information from me? How do you see the solution to the problem?
