### ISSUE TITLE
Luya failed to import blocks when running "php index.php import" command

### ISSUE THREAD

**Issue by vitopuleio99** [luyadev/luya-composer#13]
### What steps will reproduce the problem?

When i run the import command on windows 10, it only import 2 blocks, while bootstrap, generic and module-cms failed to import

### What do you get instead? (A Screenshot can help us a lot!)

The errors i get are : 
 "Unable to process block definition 'vendor\luyadev\luya-bootstrap3\src\blocks'"
 "Unable to process block definition 'vendor\luyadev\luya-generic\src\blocks'"
 "Unable to process block definition 'vendor\luyadev\luya-module-cms\src\frontend\blocks'"

### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))

this is the output : 
PS C:\xampp\htdocs\dashboard\luya-kickstarter> php luyacheck.php                                                                                              PHP Fatal error:  Uncaught Error: Call to undefined function apache_get_modules() in C:\xampp\htdocs\dashboard\luya-kickstarter\luyacheck.php(22) : eval()'d code:1
Stack trace:
#0 C:\xampp\htdocs\dashboard\luya-kickstarter\luyacheck.php(22): eval()
#1 {main}
  thrown in C:\xampp\htdocs\dashboard\luya-kickstarter\luyacheck.php(22) : eval()'d code on line 1

Fatal error: Uncaught Error: Call to undefined function apache_get_modules() in C:\xampp\htdocs\dashboard\luya-kickstarter\luyacheck.php(22) : eval()'d code:1
Stack trace:
#0 C:\xampp\htdocs\dashboard\luya-kickstarter\luyacheck.php(22): eval()
#1 {main}
  thrown in C:\xampp\htdocs\dashboard\luya-kickstarter\luyacheck.php(22) : eval()'d code on line 1

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version    |  1.0.24 
| PHP Version     | 7.3.11 
| Platform   | XAMPP 
| Operating system | Windows.

**Comment by nadar** [comment]
Hey @vitopuleio99 could you please show me your composer.json and also show me your `vendor/luyadev/installer.php` file?

**Comment by vitopuleio99** [comment]
[ComposerandInstaller.zip](https://github.com/luyadev/luya-composer/files/4019784/ComposerandInstaller.zip)

Here

**Comment by nadar** [comment]
please try

```
        "luyadev/luya-core" : "^1.0",
        "luyadev/luya-module-admin" : "^2.0",
        "luyadev/luya-module-cms" : "^2.0",
        "luyadev/luya-bootstrap3" : "^1.0",
        "luyadev/luya-generic" : "^1.0"
```

isntead of

```
        "luyadev/luya-core" : "~1.0.0",
        "luyadev/luya-module-admin" : "~1.0.0",
        "luyadev/luya-module-cms" : "~1.0.0",
        "luyadev/luya-bootstrap3" : "~1.0.0",
        "luyadev/luya-generic" : "~1.0.0"
```

+ run composer update `composer update`
+ run migrate and import `php index.php migrate` and `php index.php import` - not sure how this works on windows

**Comment by vitopuleio99** [comment]
It works! thank you a lot. Now i have all blocks in the right bar.

**Comment by nadar** [comment]
nice. enjoy!
