### ISSUE TITLE
luya symlink is created as absolute path

### ISSUE THREAD

**Issue by cebe** [luyadev/luya-composer#2]
When creating a luya project, the `luya` symlink in the project directory is created as an absolute path, e.g.:

```
$ ls -la |grep luya
lrwxrwxrwx  1 cebehosting cebehosting    61 Nov  7 09:40 luya -> /home/cebe/dev/cebe.cc/luya/vendor/luyadev/luya-core/bin/luya
```

when deploying this repo to a production environment, the link is not correct anymore. ideally it should be created relative to the current path:

```
luya -> vendor/luyadev/luya-core/bin/luya
```

the code for this is here:

https://github.com/luyadev/luya-composer/blob/7cd5ceb315c151a65d5f10e61259d332fe4394ec/src/Plugin.php#L57-L59

**Comment by cebe** [comment]
assuming the vendor directory does never change, the fix would be to simply omit the `$this->_vendorDir . DIRECTORY_SEPARATOR` part but a more correct fix would include checking the paths and generating a relative link from it.

**Comment by nadar** [comment]
Good point. Temporary we decided to add the luya symlink into gitignore list (in luya kickstarter applications), as the composer plugin will then create a working symlink in production environment.

**Comment by boehsermoe** [comment]
I have also a problem with the absolute path with the block path here: https://github.com/luyadev/luya-composer/blob/2bb82f3f78f8ad4fcb7ff01a7afb31fcebfbfbbc/src/Installer.php#L87

In my case the composer install will happen in a separate job while the deployment. So the block path will generate like `/build/project/vendor/luyadev/luya-bootstrap3/src/blocks` but in the production the path have to be `/var/www/html/vendor/luyadev/luya-bootstrap3/src/blocks`.

**Comment by nadar** [comment]
@boehsermoe what would you suggest in order to fix this?

**Comment by boehsermoe** [comment]
I think there is a simple solution: instead of `$this->vendorDir` just use `"@vendor"` because the function [handleBlockDefinitions](https://github.com/luyadev/luya-module-cms/blob/4c1f8fd19b8ca039058f9fe94f3bffedf071069d/src/admin/importers/BlockImporter.php#L81) already support aliases. 
But I am not sure that the package config blocks will be used some where other also?

**Comment by boehsermoe** [comment]
And in https://github.com/luyadev/luya-composer/blob/2bb82f3f78f8ad4fcb7ff01a7afb31fcebfbfbbc/src/Plugin.php#L40
just add \Composer\Config::RELATIVE_PATHS as flag parameter

```
$this->_vendorDir = rtrim($composer->getConfig()->get('vendor-dir', \Composer\Config::RELATIVE_PATHS), '/');
```
